baseURL = "http://127.0.0.1:1313"

environment = "development"

buildDrafts = true
buildFuture = true
buildExpired = true

[server]
    [server.headers]
        for = "/**"
        [server.headers.values]
            X-Frame-Options = "DENY"
            X-Content-Type-Options = "nosniff"
            Referrer-Policy = "no-referrer"
            Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
            Content-Security-Policy = "default-src 'none'; style-src 'self'; img-src 'self'; script-src 'self'; connect-src 'self'; font-src 'self'; base-uri 'self'; form-action 'self'; frame-src 'self'; frame-ancestors 'self'; object-src 'none'; upgrade-insecure-requests;"
